eureka:
  client:
    serviceUrl:defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: service-feign
  zipkin:
      base-url: http://localhost:8771
  sleuth:
      sampler:
        percentage: 1.0
