eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: service-zuul


zuul:
  routes:
    hi-route:
      path: /service-hi/**
      service-id: service-hi

ribbon:
    eureka:
      enabled: false

service-hi:
    ribbon:
      listOfServers: localhost:8762