eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.6.14:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: service-zuul


zuul:
  routes:
    servier-a:
      path: /service-hi/**
      service-id: service-hi
#
#ribbon:
#    eureka:
#      enabled: false

#service-hi:
#    ribbon:
#      listOfServers: localhost:8762,localhost:8763