eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: service-ribbon


zuul:
  routes:
    service-hi:
      path: /service-hi/*
      url: http://localhost:8762/