eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.6.14:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 8763
spring:
  application:
    name: service-hi