eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: service-config


spring.cloud.config.server.git.uri: https://github.com/waitupon/dwh-config.git